# Generated by Django 5.0.6 on 2024-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_application_application_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
