# Generated by Django 5.0.6 on 2024-06-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_application_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='state',
        ),
    ]
