# Generated by Django 5.0.6 on 2024-08-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_application_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='remarks',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='subject',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
