# Generated by Django 5.0.6 on 2024-08-01 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_application_remarks_alter_application_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
