const Departments = [
    'ADCPS',
    'Aerospace Engineering',
    'Biosciences and Bioengineering',
    'Centre for Research in Nanotechnology and Science (CRNTS)',
    'Chemical Engineering',
    'Chemistry Department',
    'Civil Engineering',
    'Climate Studies',
    'CMINDS',
    'CSE',
    'CSRE',
    'CTARA',
    'Department of Economics',
    'Department of Electrical Engineering',
    'Department of Energy Science and Engineering',
    'Department of HSS',
    'Department of Mechanical Engineering',
    'Department of Metallurgical Engineering and Materials Science',
    'Department of Physics',
    'DSSE',
    'Earth Sciences',
    'Educational Technology',
    'Environmental Science and Engineering Department',
    'IDC School of Design',
    'IEOR',
    'Koita Centre for Digital',
    'Mathematics Department',
    'Shailesh J. Mehta School of Management',
    'Systems and Control Engineering',
    'Other'
];

export default Departments;
